package hpke

// Pinned-byte Known Answer Test (KAT) for the HPKE one-stage SHAKE256
// key schedule used by HPKE-10-KE and HPKE-11-KE in production.
//
// The pinned hex values for HPKE-10-KE were originally generated by
// running keySchedule itself (commit 940bd02). That protects against
// future regressions but does NOT validate that the production code
// ever matched the spec in the first place — a consistent misread at
// commit time would survive the pinned check because nothing in the
// test was structurally independent of the helpers under test.
//
// This file therefore also carries referenceSHAKE256KeySchedule, a
// reference implementation of the draft-ietf-hpke-pq §5 / RFC 9180
// §5.1 mode_base key schedule written straight from the spec using
// only encoding/binary and golang.org/x/crypto/sha3. It intentionally
// does NOT call keySchedule, labeledDerive, lengthPrefixed,
// hpkeSuiteID, or concat. Each test asserts the three-way equality:
//
//   reference == production == pinned hex
//
// If any pair diverges, the test fails and names which comparison
// broke. If reference and production diverge while pinned hex still
// matches production, the reference is the one to trust until the
// pinned bytes are re-derived against an independent source (e.g.
// cloudflare/circl once #553 lands and ships a SHAKE256 HPKE suite).
//
// Byte layout, transliterated from draft-ietf-hpke-pq §5:
//
//   suite_id     = "HPKE" || I2OSP(kem_id,2) || I2OSP(kdf_id,2) || I2OSP(aead_id,2)
//   psk = psk_id = "" for mode_base
//   secrets      = I2OSP(len(psk),2) || psk || I2OSP(len(shared_secret),2) || shared_secret
//   context      = I2OSP(mode_base,1) || I2OSP(len(psk_id),2) || psk_id || I2OSP(len(info),2) || info
//   derive_input = secrets || "HPKE-v1" || suite_id ||
//                  I2OSP(len("secret"),2) || "secret" || I2OSP(L,2) || context
//   key_and_nonce = SHAKE256(derive_input, L = Nk + Nn + Nh)
//   key          = key_and_nonce[0 : Nk]
//   base_nonce   = key_and_nonce[Nk : Nk+Nn]
//
// If an edit drifts any production helper from the spec, the
// production path will disagree with this reference and the test will
// name the offending comparison.

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/sha3"
)

// referenceSHAKE256KeySchedule hand-implements the one-stage SHAKE256
// HPKE key schedule per draft-ietf-hpke-pq §5 / RFC 9180 §5.1
// mode_base. It exists solely to cross-check keySchedule in this test
// file; it is compiled only into the test binary (this is a _test.go
// file) and is unreachable from production callers.
//
// The reference intentionally bypasses every production helper
// (labeledDerive, lengthPrefixed, hpkeSuiteID, concat) and hardcodes
// the "HPKE-v1" version label and 0x0011 SHAKE256 KDF id. A bug in
// any of those helpers that the production pinned-bytes KAT shares
// would still be caught here because the reference reads the spec,
// not the code.
func referenceSHAKE256KeySchedule(kemID, aeadID uint16, Nk, Nn, Nh int, sharedSecret, info []byte) (key, baseNonce []byte) {
	// suite_id = "HPKE" || I2OSP(kem_id,2) || I2OSP(0x0011,2) || I2OSP(aead_id,2)
	suiteID := append([]byte{}, []byte("HPKE")...)
	suiteID = binary.BigEndian.AppendUint16(suiteID, kemID)
	suiteID = binary.BigEndian.AppendUint16(suiteID, 0x0011)
	suiteID = binary.BigEndian.AppendUint16(suiteID, aeadID)

	// secrets = I2OSP(0,2) || I2OSP(len(ss),2) || ss
	secrets := make([]byte, 0, 4+len(sharedSecret))
	secrets = binary.BigEndian.AppendUint16(secrets, 0)
	secrets = binary.BigEndian.AppendUint16(secrets, uint16(len(sharedSecret)))
	secrets = append(secrets, sharedSecret...)

	// context = mode_base || I2OSP(0,2) || I2OSP(len(info),2) || info
	context := make([]byte, 0, 5+len(info))
	context = append(context, 0x00)
	context = binary.BigEndian.AppendUint16(context, 0)
	context = binary.BigEndian.AppendUint16(context, uint16(len(info)))
	context = append(context, info...)

	const label = "secret"
	L := Nk + Nn + Nh

	// derive_input = secrets || "HPKE-v1" || suite_id ||
	//                I2OSP(len(label),2) || label || I2OSP(L,2) || context
	deriveInput := make([]byte, 0, len(secrets)+7+len(suiteID)+2+len(label)+2+len(context))
	deriveInput = append(deriveInput, secrets...)
	deriveInput = append(deriveInput, []byte("HPKE-v1")...)
	deriveInput = append(deriveInput, suiteID...)
	deriveInput = binary.BigEndian.AppendUint16(deriveInput, uint16(len(label)))
	deriveInput = append(deriveInput, []byte(label)...)
	deriveInput = binary.BigEndian.AppendUint16(deriveInput, uint16(L))
	deriveInput = append(deriveInput, context...)

	out := make([]byte, L)
	sha3.ShakeSum256(out, deriveInput)

	return out[:Nk], out[Nk : Nk+Nn]
}

// katSharedSecret / katInfo mirror the shape used in hpke_test.go,
// mimicking the JOSE-HPKE info bytes the top-level package passes
// through (see draft-ietf-jose-hpke-encrypt §6.1). The info payload
// intentionally mentions "A256GCM" even in the HPKE-11-KE (ChaCha)
// test — info is an opaque blob to keySchedule, so reusing one
// constant keeps the two KATs byte-comparable modulo the AEAD id
// difference that flows into suite_id.
var (
	katSharedSecret = bytes.Repeat([]byte{0xab}, 32)
	katInfo         = []byte("JOSE-HPKE rcpt\xffA256GCM\xff")
)

// AEAD ids per IANA HPKE registry. Duplicated from aead.go's ID()
// methods so the test asserts exact wire bytes without depending on
// NewAES256GCMAEAD / NewChaCha20Poly1305AEAD returning the right id.
const (
	aeadIDAES256GCM        uint16 = 0x0002
	aeadIDChaCha20Poly1305 uint16 = 0x0003
)

func TestKeyScheduleKAT_HPKE10KE(t *testing.T) {
	// Belt-and-braces: if versionLabel is renamed, the reference (which
	// hardcodes "HPKE-v1") would silently desync from production. Make
	// that failure mode loud.
	require.Equal(t, "HPKE-v1", versionLabel, `reference assumes versionLabel "HPKE-v1"`)

	const Nk, Nn, Nh = 32, 12, 64
	refKey, refNonce := referenceSHAKE256KeySchedule(
		KEMIDMLKEM768X25519,
		aeadIDAES256GCM,
		Nk, Nn, Nh,
		katSharedSecret, katInfo,
	)

	prodKey, prodNonce, err := keySchedule(SuiteHPKE10KE(), katSharedSecret, katInfo)
	require.NoError(t, err, "keySchedule")

	require.Equal(t, refKey, prodKey, "production key must match hand-written reference")
	require.Equal(t, refNonce, prodNonce, "production base_nonce must match hand-written reference")

	// Pinned expected values were originally generated from the
	// production code and are preserved as a third witness. After the
	// reference comparison above, re-deriving these against a truly
	// external source (e.g. cloudflare/circl once #553 lands) would
	// add a fourth.
	wantKey, err := hex.DecodeString("57b5aedbc389ec4851cbe3f7c28dc1406d84d8644f7d48a03edf4239c761caa6")
	require.NoError(t, err)
	wantNonce, err := hex.DecodeString("8e91df4d9768c2a882ac37ee")
	require.NoError(t, err)

	require.Equal(t, wantKey, refKey, "reference key must match pinned hex")
	require.Equal(t, wantNonce, refNonce, "reference base_nonce must match pinned hex")
}

func TestKeyScheduleKAT_HPKE11KE(t *testing.T) {
	require.Equal(t, "HPKE-v1", versionLabel, `reference assumes versionLabel "HPKE-v1"`)

	const Nk, Nn, Nh = 32, 12, 64
	refKey, refNonce := referenceSHAKE256KeySchedule(
		KEMIDMLKEM768X25519,
		aeadIDChaCha20Poly1305,
		Nk, Nn, Nh,
		katSharedSecret, katInfo,
	)

	prodKey, prodNonce, err := keySchedule(SuiteHPKE11KE(), katSharedSecret, katInfo)
	require.NoError(t, err, "keySchedule")

	require.Equal(t, refKey, prodKey, "production key must match hand-written reference")
	require.Equal(t, refNonce, prodNonce, "production base_nonce must match hand-written reference")

	// Pinned expected values derived from the reference function above
	// on first run. The reference is structurally independent of
	// production, so these bytes are anchored to a from-spec read of
	// draft-ietf-hpke-pq §5, not to whatever keySchedule happens to
	// produce.
	wantKey, err := hex.DecodeString("52a9080bc07d54db68aef5b9f78058e6dffdb8bb1bc70e787ba9c8ca6914ddbc")
	require.NoError(t, err)
	wantNonce, err := hex.DecodeString("d29ee380616ac8cead399b49")
	require.NoError(t, err)

	require.Equal(t, wantKey, refKey, "reference key must match pinned hex")
	require.Equal(t, wantNonce, refNonce, "reference base_nonce must match pinned hex")
}
